### ISSUE TITLE
[linux] panic at startup: gtk_icon_theme_get_for_screen failed

### ISSUE THREAD

**Issue by tuananh** [evilsocket/clipbud#2]
Using the example config in readme.

Setup: archlinux/i3. Trying building from src, same issue.

```
RUST_BACKTRACE=1 clipbud -c clipbud-config.toml
loading config from: clipbud-config.toml
clipboard observer started...

(process:78783): Gtk-CRITICAL **: 07:15:42.737: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:78783): GLib-GObject-CRITICAL **: 07:15:42.737: invalid (NULL) pointer instance

(process:78783): GLib-GObject-CRITICAL **: 07:15:42.737: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

thread 'main' panicked at /home/anh/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gtk-0.18.2/src/auto/menu.rs:29:9:
GTK has not been initialized. Call `gtk::init` first.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted                    (core dumped) RUST_BACKTRACE=1 clipbud -c clipbud-config.toml
```

if i do gtk::init myself (after `crate add gtk`), it runs but the windows is black

```
diff --git a/src/ui/tray.rs b/src/ui/tray.rs
index 6f44b72..42c2945 100644
--- a/src/ui/tray.rs
+++ b/src/ui/tray.rs
@@ -4,6 +4,8 @@ use tray_icon::{
 };

 pub(crate) fn build_tray_menu_icon() -> anyhow::Result<(TrayIcon, MenuItem)> {
+    gtk::init().unwrap();
+
     let tray_menu = Menu::new();
     let quit_menu_item = MenuItem::new("Quit", true, None);
```

which looks like this

<img width="1035" height="723" alt="Image" src="https://github.com/user-attachments/assets/cd69324d-41f0-4cc9-8759-c567aa18128d" />

At this point, I guess, it's because I'm using i3 and the way this work clipbud makes itself visible / off screen but i3 force its to show (because tiling window manager)

**Comment by evilsocket** [comment]
thanks for reporting @tuananh! i'm out in the woods for a few days so no access to a linux computer, will test and hopefully fix as soon as i'm back home

**Comment by tuananh** [comment]
I'm curious to why you want to do the show/hide window by moving it on/off viewport while we can do this

```
ctx.send_viewport_cmd(egui::ViewportCommand::Visible(true));
```

**Comment by evilsocket** [comment]
> I'm curious to why you want to do the show/hide window by moving it on/off viewport while we can do this
> 
> ```
> ctx.send_viewport_cmd(egui::ViewportCommand::Visible(true));
> ```

Because this is my first egui project and i'm still figuring a lot of it out :D thanks for the tip, keep sending them if you see weird stuff in the code <3

**Comment by evilsocket** [comment]
Oook, now i remember exactly why! I tried to do what you said initially, however that only hid the internal window, the outer frame somehow was still visible. I just found out that the best way to do it is:

> ctx.send_viewport_cmd_to(egui::ViewportId::ROOT, egui::ViewportCommand::Visible(false));

**Comment by c4nc** [comment]
Hey Simone,
FYI, just got similar issue on arch/wayland (hyprland) (installed with cargo):

```
RUST_BACKTRACE=full clipbud                                          9:54:18
loading config from: /home/c4/.clipbud/config.yaml

(process:73638): libayatana-appindicator-WARNING **: 09:54:27.089: libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
clipboard observer started...

(process:73638): Gtk-CRITICAL **: 09:54:27.089: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:73638): GLib-GObject-CRITICAL **: 09:54:27.089: invalid (NULL) pointer instance

(process:73638): GLib-GObject-CRITICAL **: 09:54:27.089: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

thread 'main' panicked at /home/c4/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gtk-0.18.2/src/auto/menu.rs:29:9:
GTK has not been initialized. Call `gtk::init` first.
stack backtrace:
   0:      0x8b931710772 - <unknown>
   1:      0x8b931284583 - <unknown>
   2:      0x8b9317102ff - <unknown>
   3:      0x8b9317105d3 - <unknown>
   4:      0x8b93170ffc1 - <unknown>
   5:      0x8b93174a2a5 - <unknown>
   6:      0x8b93174a239 - <unknown>
   7:      0x8b93174aa8c - <unknown>
   8:      0x8b93103d1ff - <unknown>
   9:      0x8b931443bdd - <unknown>
  10:      0x8b931443c5d - <unknown>
  11:      0x8b93179a1fc - <unknown>
  12:      0x8b9310dfbf5 - <unknown>
  13:      0x8b9310a0c93 - <unknown>
  14:      0x8b9310e3885 - <unknown>
  15:     0x6f312b027675 - <unknown>
  16:     0x6f312b027729 - __libc_start_main
  17:      0x8b931093bd5 - <unknown>
  18:                0x0 - <unknown>
[1]    73638 IOT instruction (core dumped)  RUST_BACKTRACE=full clipbud
```

**Comment by evilsocket** [comment]
hey @c4nc thanks for reporting! i'll be able to test on linux starting tomorrow, in the meantime i pushed an attempted fix calling gtk:init ... idk if it'll compile and work, but it's a start! i'll make sure everything works on every platform before releasing 1.0.0

**Comment by c4nc** [comment]
> hey [@c4nc](https://github.com/c4nc) thanks for reporting! i'll be able to test on linux starting tomorrow, in the meantime i pushed an attempted fix calling gtk:init ... idk if it'll compile and work, but it's a start! i'll make sure everything works on every platform before releasing 1.0.0

I can confirm that the `git` version compiles and runs ✅  

I’m still facing some issues that seem related to how it interacts with Wayland/Hyprland, but I’ll test it out further with different config options and open a dedicated issue if needed.

**Comment by evilsocket** [comment]
nice! @c4nc how's the UI on linux? it's supposed to start hidden and only show up when the hotkey is pressed, and hide on ESC or when the mouse moves outside of its window ... if you can confirm that's the case we can close this and work on separate, more specific issues.

**Comment by c4nc** [comment]
@evilsocket nope, still hitting issues on Wayland/Hyprland:

- On start, it draws a **black window** (both with and without the `hotkey` config key).  
- With `hide_on_mouse_outside_window: true`, it conflicts with Hyprland’s tiling / mouse-focus behavior → results in **flickering** whenever the mouse moves.  
- If I set `hide_on_mouse_outside_window: false`, then once a text is copied and while keeping focus on the clipbud window, hitting **ESC** brings it back to the black window state.

**Comment by c4nc** [comment]
@evilsocket  
The most "stable" setup I’ve found so far (at least on my Hyprland environment) is with the following config:  

- `hotkey` set  
- `wrap_buttons: none`  
- `hide_on_mouse_outside_window: false`  

With this setup, the app still shows up as a small **black window** (centered on screen, floating / not tiled), but at least it doesn’t flicker or conflict with the tiling/mouse-focus behavior anymore.

**Comment by tuananh** [comment]
@c4nc does your tray icon work? Mine does not. I'm using i3 with i3status-rs

**Comment by evilsocket** [comment]
guys if you feel like it, it'd be nice to have you on the discord and keep the conversation going in the project channel -> https://discord.com/channels/1100085665766572142/1414585607564300439

**Comment by c4nc** [comment]
@evilsocket no sign of icon on my [waybar](https://github.com/Alexays/Waybar/)

**Comment by c4nc** [comment]
> guys if you feel like it, it'd be nice to have you on the discord and keep the conversation going in the project channel -> https://discord.com/channels/1100085665766572142/1414585607564300439
@evilsocket 

<img width="1487" height="1292" alt="Image" src="https://github.com/user-attachments/assets/ddde1108-fe1e-4846-9cd0-4b638ac88dd9" />

**Comment by evilsocket** [comment]
@c4nc 

<img width="604" height="404" alt="Image" src="https://github.com/user-attachments/assets/d786b9fd-ac38-41d8-8199-62d21c958eb1" />

**Comment by c4nc** [comment]
@evilsocket lmao :D

Just sent you my Discord username on LinkedIn chat, or you can reach me on X (@c4nc) if you prefer.

**Comment by tuananh** [comment]
> // Since egui uses winit under the hood and doesn't use gtk on Linux, and we need gtk for
>    // the tray icon to show up, we need to spawn a thread
>   // where we initialize gtk and create the tray_icon

I think this is why. Running the below example, I can get the tray icon

cc @evilsocket 

ref: https://github.com/tauri-apps/tray-icon/blob/dev/examples/egui.rs
